import { useState, useMemo } from "react";
import { GitCompare, X, ArrowRight, Copy, Check } from "lucide-react";
import { useAppStore } from "@/stores/app-store";
import { getTables, getColumns } from "@/lib/tauri-commands";
import { t } from "@/lib/i18n";

interface SchemaDiffDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

interface TableDiff {
  name: string;
  status: "only_source" | "only_target" | "modified";
  sourceColumns?: { name: string; dataType: string; nullable: boolean }[];
  targetColumns?: { name: string; dataType: string; nullable: boolean }[];
  columnDiffs?: {
    name: string;
    status: "only_source" | "only_target" | "modified";
    sourceType?: string;
    targetType?: string;
  }[];
}

function SchemaDiffDialog({ isOpen, onClose }: SchemaDiffDialogProps) {
  const { connections } = useAppStore();
  const connectedConns = connections.filter((c) => c.connected);

  const [sourceId, setSourceId] = useState<string>("");
  const [targetId, setTargetId] = useState<string>("");
  const [diffs, setDiffs] = useState<TableDiff[]>([]);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleCompare = async () => {
    if (!sourceId || !targetId || sourceId === targetId) return;

    setLoading(true);
    setError(null);
    setDiffs([]);

    try {
      const [sourceTables, targetTables] = await Promise.all([
        getTables(sourceId),
        getTables(targetId),
      ]);

      const sourceMap = new Map(sourceTables.map((t) => [t.name, t]));
      const targetMap = new Map(targetTables.map((t) => [t.name, t]));
      const allNames = new Set([...sourceMap.keys(), ...targetMap.keys()]);
      const result: TableDiff[] = [];

      for (const name of allNames) {
        const inSource = sourceMap.has(name);
        const inTarget = targetMap.has(name);

        if (inSource && !inTarget) {
          result.push({ name, status: "only_source" });
        } else if (!inSource && inTarget) {
          result.push({ name, status: "only_target" });
        } else {
          // Both exist - compare columns
          try {
            const [srcCols, tgtCols] = await Promise.all([
              getColumns(sourceId, name, sourceMap.get(name)?.schema),
              getColumns(targetId, name, targetMap.get(name)?.schema),
            ]);

            const srcColMap = new Map(srcCols.map((c) => [c.name, c]));
            const tgtColMap = new Map(tgtCols.map((c) => [c.name, c]));
            const allColNames = new Set([...srcColMap.keys(), ...tgtColMap.keys()]);
            const colDiffs: TableDiff["columnDiffs"] = [];

            for (const colName of allColNames) {
              const inSrc = srcColMap.has(colName);
              const inTgt = tgtColMap.has(colName);

              if (inSrc && !inTgt) {
                colDiffs.push({ name: colName, status: "only_source" });
              } else if (!inSrc && inTgt) {
                colDiffs.push({ name: colName, status: "only_target" });
              } else {
                const src = srcColMap.get(colName)!;
                const tgt = tgtColMap.get(colName)!;
                if (src.dataType !== tgt.dataType || src.nullable !== tgt.nullable) {
                  colDiffs.push({
                    name: colName,
                    status: "modified",
                    sourceType: `${src.dataType}${src.nullable ? "" : " NOT NULL"}`,
                    targetType: `${tgt.dataType}${tgt.nullable ? "" : " NOT NULL"}`,
                  });
                }
              }
            }

            if (colDiffs.length > 0) {
              result.push({ name, status: "modified", columnDiffs: colDiffs });
            }
          } catch {
            // Skip column comparison on error
          }
        }
      }

      setDiffs(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : t('diff.compareFailed'));
    } finally {
      setLoading(false);
    }
  };

  const generateMigrationSql = useMemo(() => {
    if (diffs.length === 0) return "";

    const lines: string[] = [t('diff.autoGeneratedComment'), t('diff.reviewComment')];

    for (const diff of diffs) {
      if (diff.status === "only_source") {
        lines.push(t('diff.onlySourceComment', { name: diff.name }));
        lines.push(`-- DROP TABLE IF EXISTS "${diff.name}";\n`);
      } else if (diff.status === "only_target") {
        lines.push(t('diff.onlyTargetComment', { name: diff.name }));
        lines.push(t('diff.manualCreateComment'));
      } else if (diff.columnDiffs) {
        lines.push(t('diff.hasDiffComment', { name: diff.name }));
        for (const col of diff.columnDiffs) {
          if (col.status === "only_source") {
            lines.push(`ALTER TABLE "${diff.name}" DROP COLUMN IF EXISTS "${col.name}";`);
          } else if (col.status === "only_target") {
            lines.push(`ALTER TABLE "${diff.name}" ADD COLUMN "${col.name}" ${col.targetType || "TEXT"};`);
          } else if (col.status === "modified") {
            lines.push(`ALTER TABLE "${diff.name}" ALTER COLUMN "${col.name}" TYPE ${col.targetType || "TEXT"};`);
          }
        }
        lines.push("");
      }
    }

    return lines.join("\n");
  }, [diffs]);

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMigrationSql);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/50" onClick={onClose} />
      <div className="relative w-[600px] max-h-[80vh] bg-background border border-border rounded-lg shadow-xl flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border shrink-0">
          <div className="flex items-center gap-2">
            <GitCompare size={15} className="text-muted-foreground" />
            <span className="text-sm font-medium text-foreground">{t('diff.title')}</span>
          </div>
          <button onClick={onClose} className="p-1 rounded text-muted-foreground hover:text-foreground hover:bg-muted transition-colors">
            <X size={14} />
          </button>
        </div>

        <div className="px-4 py-3 space-y-3 overflow-y-auto flex-1">
          {/* Connection selectors */}
          <div className="flex items-center gap-2">
            <div className="flex-1 space-y-1">
              <label className="text-xs text-muted-foreground">{t('diff.source')}</label>
              <select
                value={sourceId}
                onChange={(e) => setSourceId(e.target.value)}
                className="w-full px-2 py-1.5 text-xs bg-muted border border-border rounded outline-none text-foreground"
              >
                <option value="">{t('diff.selectConnection')}</option>
                {connectedConns.map((c) => (
                  <option key={c.id} value={c.id}>{c.name}</option>
                ))}
              </select>
            </div>
            <ArrowRight size={16} className="text-muted-foreground mt-4" />
            <div className="flex-1 space-y-1">
              <label className="text-xs text-muted-foreground">{t('diff.target')}</label>
              <select
                value={targetId}
                onChange={(e) => setTargetId(e.target.value)}
                className="w-full px-2 py-1.5 text-xs bg-muted border border-border rounded outline-none text-foreground"
              >
                <option value="">{t('diff.selectConnection')}</option>
                {connectedConns.map((c) => (
                  <option key={c.id} value={c.id}>{c.name}</option>
                ))}
              </select>
            </div>
          </div>

          <button
            onClick={handleCompare}
            disabled={!sourceId || !targetId || sourceId === targetId || loading}
            className="w-full py-1.5 text-xs bg-[hsl(var(--tab-active))] text-white rounded hover:opacity-90 transition-opacity disabled:opacity-40"
          >
            {loading ? t('diff.comparing') : t('diff.startCompare')}
          </button>

          {error && (
            <div className="px-2.5 py-1.5 rounded text-xs bg-destructive/10 text-destructive">{error}</div>
          )}

          {/* Results */}
          {diffs.length > 0 && (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs text-muted-foreground">
                  {t('diff.foundDiffs', { count: String(diffs.length) })}
                </span>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1 px-2 py-0.5 text-[10px] text-muted-foreground hover:text-foreground hover:bg-muted rounded transition-colors"
                >
                  {copied ? <Check size={10} /> : <Copy size={10} />}
                  {copied ? t('diff.copied') : t('diff.copyMigration')}
                </button>
              </div>

              <div className="border border-border rounded overflow-hidden">
                <table className="w-full text-xs">
                  <thead className="bg-muted">
                    <tr>
                      <th className="px-3 py-1.5 text-left font-medium text-muted-foreground">{t('diff.tableName')}</th>
                      <th className="px-3 py-1.5 text-left font-medium text-muted-foreground">{t('diff.status')}</th>
                      <th className="px-3 py-1.5 text-left font-medium text-muted-foreground">{t('diff.details')}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {diffs.map((diff) => (
                      <tr key={diff.name} className="border-t border-border/50">
                        <td className="px-3 py-1.5 text-foreground font-mono">{diff.name}</td>
                        <td className="px-3 py-1.5">
                          <span className={`text-[10px] px-1.5 py-0.5 rounded ${
                            diff.status === "only_source"
                              ? "bg-destructive/10 text-destructive"
                              : diff.status === "only_target"
                              ? "bg-blue-500/10 text-blue-500"
                              : "bg-yellow-500/10 text-yellow-500"
                          }`}>
                            {diff.status === "only_source"
                              ? t('diff.onlySource')
                              : diff.status === "only_target"
                              ? t('diff.onlyTarget')
                              : t('diff.hasDiff')}
                          </span>
                        </td>
                        <td className="px-3 py-1.5 text-muted-foreground">
                          {diff.columnDiffs?.map((c) => (
                            <div key={c.name} className="text-[10px]">
                              {c.status === "only_source" && `${t('diff.missingColumns')}${c.name}`}
                              {c.status === "only_target" && `${t('diff.newColumns')}${c.name}`}
                              {c.status === "modified" && `${c.name}: ${c.sourceType} -> ${c.targetType}`}
                            </div>
                          ))}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Migration SQL */}
              <div className="space-y-1">
                <label className="text-xs text-muted-foreground">{t('diff.migrationSql')}</label>
                <pre className="p-2 text-[10px] bg-muted rounded border border-border overflow-auto max-h-40 font-mono text-foreground whitespace-pre-wrap">
                  {generateMigrationSql}
                </pre>
              </div>
            </div>
          )}

          {diffs.length === 0 && !loading && sourceId && targetId && sourceId !== targetId && (
            <div className="text-xs text-muted-foreground text-center py-4">
              {t('diff.noDiffs')}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default SchemaDiffDialog;
